version: '3'

volumes:
  produtosdata:

networks:
  backend:
  frontend:

services:
  database:
    image: "mysql:5.7.36"
    environment:
      - MYSQL_ROOT_PASSWORD=numsey
      - bind-adress=0.0.0.0
    volumes:
      - produtosdata:/var/lib/mysql
      - ./init_sql:/docker-entrypoint-initdb.d
    networks:
      - backend